// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateReq struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}
